server:
  port: 8080
  servlet:
    #    context-path: /api
    #    encoding:
    #      charset: UTF-8
    session:
      timeout: 100m


mybatis:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*xml



spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    hikari:
      maximum-pool-size: 10
      auto-commit: true
logging:
  config: classpath:log4j2.xml

